name: Netlify build manual deploy comment

on:
  issue_comment:
    types: [created]

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      # we use `jq` to parse the GH API response
      - name: 'Setup jq'
        uses: dcarbone/install-jq-action@v2

      - name: send request to Netlify build hook
        env: 
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # when a contributor comments 'netlify build',
        # but only on pull requests, not issues
        if: |
          contains(github.event.comment.body, 'netlify build')
          && ${{ github.event.issue.pull_request }}
        run: |
          gh api \
          $(echo ${{ github.event.issue.pull_request.url }} | sed 's/https:\/\/api.github.com//') \
          | jq .head.ref
        # echo "GITHUB_HEAD_REF: ${GITHUB_HEAD_REF}"
        # echo "GITHUB_REF: ${GITHUB_REF}"
        # echo 'github.event.comment.url: ${{ github.event.comment.url }}'
        # echo 'github.event.issue.id: ${{ github.event.issue.id }}'
        # echo 'github.refname: ${{ github.ref_name }}'
        # echo 'github.event.number: ${{ github.event.number }}'
        # echo 'github.event.pull_request.base.ref: ${{github.event.pull_request.base.ref}}'
        # curl -X POST \
        # https://api.netlify.com/build_hooks/${{ secrets.NETLIFY_BUILD_HOOK_ID }}?trigger_branch=${{ github.ref_name }}&trigger_title=Deploy%20preview%20for%20PR%20${{ github.event.number }}

      - name: Comment for Netlify to update with preview URL
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            > Netlify Preview Deployment Information

            > This comment will auto update when your preview build is ready!