name: Netlify build manual deploy comment

on:
  issue_comment:
    types: [created]

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      # we use `jq` to parse the GH API response
      - name: 'Setup jq'
        uses: dcarbone/install-jq-action@v2

      - name: send request to Netlify build hook
        env: 
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # when a contributor comments 'netlify build',
        # but only on pull requests, not issues
        if: |
          contains(github.event.comment.body, 'netlify build')
          && ${{ github.event.issue.pull_request }}
        run: |
          branch_name=$(\
            gh api \
            $(echo ${{ github.event.issue.pull_request.url }} | sed 's/https:\/\/api.github.com//') \
            | jq -r .head.ref \
          )

          curl -X POST \
          "https://api.netlify.com/build_hooks/${{ secrets.NETLIFY_BUILD_HOOK_ID }}?trigger_branch=$branch_name" '&trigger_title=Deploy+preview+for+PR+${{ github.event.number }}'

      - name: Comment for Netlify to update with preview URL
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            > Netlify Preview Deployment Information

            > This comment will auto update when your preview build is ready!